// Code generated by goctl. DO NOT EDIT.
package types

type ProductCreateRequest struct {
	Name          string `form:"name"`
	CategoryId    uint   `form:"categoryId"`
	Title         string `form:"title"`
	Info          string `form:"info"`
	Price         string `form:"price"`
	DiscountPrice string `form:"discountPrice"`
	Onsale        bool   `form:"onsale"`
	Num           int    `form:"num"`
}

type ProductListRequset struct {
	CategoryId int `form:"categoryId"`
	PageNum    int `form:"pageNum"`
	PageSize   int `form:"pageSize"`
}

type ProductSelectRequst struct {
	Info string `form:"info"`
}

type ProductShowRequst struct {
	Id int `form:"id"`
}

type ProductImgRequest struct {
	Id int `form:"id"`
}

type Response struct {
	Status int         `json:"status"`
	Data   interface{} `json:"data"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}

type ResponseList struct {
	Data   interface{} `json:"data"`
	Total  int         `json:"total"`
	Status int         `json:"status"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}
