// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"E-commerce_system/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: OrderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/show",
				Handler: OrderGetHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/order/delete",
				Handler: OrderDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/pay",
				Handler: PayOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
