// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"E-commerce_system/address/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/address/create",
				Handler: AddressCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/show",
				Handler: AddressGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/address/update",
				Handler: AddressUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/addresses/delete",
				Handler: AddressDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/addresses/list",
				Handler: AddressListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
