// Code generated by goctl. DO NOT EDIT.
package types

type CartCreateRequset struct {
	BossId    int `form:"bossId"`
	ProductId int `form:"productId"`
	Num       int `form:"num"`
}

type CartUpdateRequest struct {
	Num int `form:"num"`
	Id  int `form:"id"`
}

type CartDeleteRequest struct {
	Id int `form:"id"`
}

type CartGetIdResquest struct {
	Id int `form:"id"`
}

type Response struct {
	Status int         `json:"status"`
	Data   interface{} `json:"data"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}
