// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Key      string `form:"key"`
}

type UserRegisterRequest struct {
	Nickname string `form:"nick_name"`
	Username string `form:"user_name"`
	Password string `form:"password"`
	Key      string `form:"key"`
}

type UserUpdateNickRequest struct {
	Nickname string `form:"nickname"`
}

type UserImageUplaodRequest struct {
}

type UserSendEmail struct {
	Email         string `form:"email"`
	Password      string `form:"password"`
	OperationType string `form:"operationType"`
}

type UserValidEmail struct {
	Token string `form:"token"`
}

type Response struct {
	Status int         `json:"status"`
	Data   interface{} `json:"data"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}
