// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"E-commerce_system/product/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth.ProJwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/product/create",
					Handler: ProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/product/list",
					Handler: ProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product/search",
					Handler: ProductSelectHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/product/:id",
					Handler: ProductShowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/img/:id",
					Handler: ProductImgHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/category/:id",
					Handler: ProductCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
