// Code generated by goctl. DO NOT EDIT.
package types

type AddressCreateRequest struct {
	Name    string `form:"name"`
	Address string `form:"address"`
	Phone   string `form:"phone"`
}

type AddressUpdateRequest struct {
	Name    string `form:"name"`
	Address string `form:"address"`
	Phone   string `form:"phone"`
	Id      int    `form:"id"`
}

type AddressDeleteRequest struct {
	Id int `form:"id"`
}

type AddressGetIdResquest struct {
	Id int `form:"id"`
}

type Response struct {
	Status int         `json:"status"`
	Data   interface{} `json:"data"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}

type ResponseList struct {
	Data   interface{} `json:"data"`
	Total  int         `json:"total"`
	Status int         `json:"status"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}
