// Code generated by goctl. DO NOT EDIT.
package types

type OrderCreate struct {
	ProductId uint `form:"productId"`
	Num       int  `form:"num"`
	AddressId int  `form:"addressId"`
	Money     int  `form:"money"`
	BossId    uint `form:"bossId"`
	UserId    uint `form:"userId"`
	OrderNum  int  `form:"orderNum"`
	Type      int  `form:"type"`
}

type OrderGetIdResquest struct {
	UserId uint `form:"userId"`
	Id     int  `form:"id"`
}

type DeleteOrderIdRequest struct {
	OrderId int `form:"orderId"`
	Userid  int `form:"userid"`
}

type PayOrderRequest struct {
	Num        int `form:"num"`
	Money      int `form:"money"`
	OrderNum   int `form:"orderNum"`
	Product_id int `form:"productId"`
	Boss_id    int `form:"bossId"`
	Order_id   int `form:"orderId"`
}

type Response struct {
	Status int         `json:"status"`
	Data   interface{} `json:"data"`
	Msg    string      `json:"msg"`
	Error  string      `json:"error"`
}
