// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"E-commerce_system/cart/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/Cart/create",
				Handler: CartCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Cart/show",
				Handler: CartGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Cart/update",
				Handler: CartUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/Cart/delete",
				Handler: CartDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Cart/list",
				Handler: CartListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
